name: student_project

channels:
    - defaults
    - conda-forge

dependencies:
    - ipykernel   = 5.1.4
    - jupyterlab  = 2.1.2
    - python      = 3.8.2

    - r-aer       = 1.2_9
    - r-base      = 4.0.0
    - r-cowplot   = 1.0.0
    - r-gt        = 0.2.1
    - r-haven     = 2.3.1
    - r-irdisplay = 0.7
    - r-irkernel  = 1.1
    - r-tidyverse = 1.3.0
    - r-yaml      = 2.2.1 
